# Generated by Django 3.0.8 on 2020-07-05 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.CharField(max_length=2555, primary_key=True, serialize=False)),
                ('real_name', models.CharField(blank=True, max_length=2555, null=True)),
                ('tz', models.CharField(blank=True, max_length=2555, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(blank=True, max_length=2555, null=True)),
                ('end_time', models.CharField(blank=True, max_length=2555, null=True)),
                ('stid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='JsonAssignment.User')),
            ],
        ),
    ]
