# Generated by Django 3.0.8 on 2020-07-05 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JsonAssignment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityperiod',
            old_name='stid',
            new_name='uid',
        ),
    ]
